<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="GitPuller.Core\**" />
    <Content Remove="GitPuller.Core\**" />
    <EmbeddedResource Remove="GitPuller.Core\**" />
    <None Remove="GitPuller.Core\**" />
    <Compile Remove="GitPuller.WinUI\**" />
    <Content Remove="GitPuller.WinUI\**" />
    <EmbeddedResource Remove="GitPuller.WinUI\**" />
    <None Remove="GitPuller.WinUI\**" />
    <Compile Remove="tests\**" />
    <Content Remove="tests\**" />
    <EmbeddedResource Remove="tests\**" />
    <None Remove="tests\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="GitPuller.Core\GitPuller.Core.csproj" />
  </ItemGroup>

</Project>
