<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="GitPuller.WinUI\**" />
    <Content Remove="GitPuller.WinUI\**" />
    <EmbeddedResource Remove="GitPuller.WinUI\**" />
    <None Remove="GitPuller.WinUI\**" />
  </ItemGroup>

</Project>
